#!/bin/bash
# check_php_version.sh - Monitor Fedora PHP version and trigger COPR rebuilds
# Checks src.fedoraproject.org for PHP version changes. When a new version is
# detected, updates php_version.json and commits+pushes to trigger COPR rebuild.
#
# Usage:
#   ./check_php_version.sh --check-only    # Check without modifying (default)
#   ./check_php_version.sh --update        # Update and push if changed
#   ./check_php_version.sh --dry-run       # Show what would happen
#   ./check_php_version.sh --force         # Force update even if unchanged

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSIONS_FILE="$SCRIPT_DIR/php_version.json"

# Fedora releases to monitor (space-separated)
FEDORA_RELEASES="f41 f42 rawhide"

MODE="check"
DRY_RUN=0
FORCE=0

while [[ $# -gt 0 ]]; do
    case $1 in
        --update) MODE="update"; shift ;;
        --check-only) MODE="check"; shift ;;
        --dry-run) DRY_RUN=1; shift ;;
        --force) FORCE=1; shift ;;
        --help)
            echo "Usage: $0 [--check-only|--update] [--dry-run] [--force]"
            echo "  --check-only  Check for PHP updates but don't modify anything (default)"
            echo "  --update      Update php_version.json and commit+push if changed"
            echo "  --dry-run     Show what would be done without making changes"
            echo "  --force       Force update even if versions haven't changed"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

get_timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Fetch the PHP spec from Fedora src repo (cached per branch per run)
fetch_spec() {
    local branch="$1"
    local cache_var="_SPEC_CACHE_${branch}"

    if [ -z "${!cache_var}" ]; then
        local spec
        spec=$(curl -sf "https://src.fedoraproject.org/rpms/php/raw/${branch}/f/php.spec" 2>/dev/null) || true
        eval "${cache_var}=\"\${spec}\""
    fi

    echo "${!cache_var}"
}

# Extract %global upver from spec (the actual PHP version, e.g. 8.4.19)
get_php_version() {
    local branch="$1"
    local spec
    spec=$(fetch_spec "$branch")

    local version
    version=$(echo "$spec" | sed -n 's/^%global[[:space:]]\+upver[[:space:]]\+//p' | head -1)

    if [ -n "$version" ]; then
        echo "$version"
        return 0
    fi

    echo "unknown"
    return 1
}

# Extract %global zendver from spec (the Zend ABI version - this is what
# actually determines whether the extension .so is compatible)
get_php_zendver() {
    local branch="$1"
    local spec
    spec=$(fetch_spec "$branch")

    local zendver
    zendver=$(echo "$spec" | sed -n 's/^%global[[:space:]]\+zendver[[:space:]]\+//p' | head -1)

    if [ -n "$zendver" ]; then
        echo "$zendver"
        return 0
    fi

    echo "unknown"
    return 1
}

# Read saved version for a given release from php_version.json
get_saved_version() {
    local release="$1"
    if [ -f "$VERSIONS_FILE" ]; then
        grep -A2 "\"${release}\"" "$VERSIONS_FILE" 2>/dev/null \
            | grep '"version"' | sed 's/.*"version":[[:space:]]*"//;s/".*//' | head -1
    fi
}

get_saved_zendver() {
    local release="$1"
    if [ -f "$VERSIONS_FILE" ]; then
        grep -A3 "\"${release}\"" "$VERSIONS_FILE" 2>/dev/null \
            | grep '"zendver"' | sed 's/.*"zendver":[[:space:]]*"//;s/".*//' | head -1
    fi
}

# Write php_version.json with all tracked releases
write_versions() {
    local timestamp="$(get_timestamp)"
    local first=1

    cat > "$VERSIONS_FILE" <<HEADER
{
  "php_versions": {
HEADER

    for release in $FEDORA_RELEASES; do
        local ver_var="NEW_VERSION_${release}"
        local zend_var="NEW_ZENDVER_${release}"
        local ver="${!ver_var}"
        local zend="${!zend_var}"

        if [ $first -eq 0 ]; then
            echo "    }," >> "$VERSIONS_FILE"
        fi
        first=0

        cat >> "$VERSIONS_FILE" <<ENTRY
    "${release}": {
      "version": "${ver}",
      "zendver": "${zend}"
ENTRY
    done

    cat >> "$VERSIONS_FILE" <<FOOTER
    }
  },
  "last_checked": "${timestamp}"
}
FOOTER
}

# Bump the release counter
bump_release() {
    local release_file="$SCRIPT_DIR/release"
    local current=1

    if [ -f "$release_file" ]; then
        current=$(cat "$release_file" | tr -d '[:space:]')
        current=$((current + 1))
    fi

    echo "$current" > "$release_file"
    echo "  Release bumped to: $current"
}

# Commit and push changes
commit_and_push() {
    local changes="$1"

    cd "$SCRIPT_DIR"

    if ! git config user.name >/dev/null 2>&1; then
        git config user.name "PHP Version Checker"
        git config user.email "bot@github-actions"
    fi

    git add php_version.json release

    local commit_msg="Auto-update: PHP version change detected

${changes}
This commit triggers automatic COPR rebuild for the new PHP version.
Generated by check_php_version.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")"

    git commit -m "$commit_msg"
    git push origin "$(git rev-parse --abbrev-ref HEAD)"
}

# === Main ===

echo "=== PHP Version Check ==="
echo "Mode: $MODE"
echo "Checking at $(get_timestamp)"
echo

VERSIONS_CHANGED=0
CHANGE_SUMMARY=""

for release in $FEDORA_RELEASES; do
    echo "Checking ${release}..."

    new_ver=$(get_php_version "$release")
    new_zend=$(get_php_zendver "$release")
    saved_ver=$(get_saved_version "$release")
    saved_zend=$(get_saved_zendver "$release")

    # Store for write_versions
    eval "NEW_VERSION_${release}=\"${new_ver}\""
    eval "NEW_ZENDVER_${release}=\"${new_zend}\""

    echo "  ${release}: PHP ${new_ver} (zend-abi ${new_zend}) [saved: ${saved_ver:-none} (${saved_zend:-none})]"

    if [ "$new_ver" != "$saved_ver" ] || [ "$new_zend" != "$saved_zend" ]; then
        if [ "$new_ver" != "unknown" ]; then
            VERSIONS_CHANGED=1
            if [ "$new_zend" != "$saved_zend" ]; then
                CHANGE_SUMMARY="${CHANGE_SUMMARY}  ${release}: ABI change! zend ${saved_zend:-none} -> ${new_zend} (PHP ${saved_ver:-none} -> ${new_ver})\n"
            else
                CHANGE_SUMMARY="${CHANGE_SUMMARY}  ${release}: PHP ${saved_ver:-none} -> ${new_ver} (zend-abi unchanged: ${new_zend})\n"
            fi
        fi
    fi
done

echo

if [ $FORCE -eq 1 ]; then
    echo "Force mode enabled"
    VERSIONS_CHANGED=1
fi

if [ $VERSIONS_CHANGED -eq 1 ]; then
    echo "=== Changes detected ==="
    echo -e "$CHANGE_SUMMARY"

    if [ "$MODE" = "update" ]; then
        if [ $DRY_RUN -eq 1 ]; then
            echo "DRY RUN: Would update php_version.json"
            echo "DRY RUN: Would commit and push"
        else
            echo "Updating php_version.json..."
            write_versions
            echo "php_version.json updated"

            echo "Bumping release counter..."
            bump_release

            echo "Committing and pushing..."
            commit_and_push "$(echo -e "$CHANGE_SUMMARY")"
            echo "Changes committed and pushed"
        fi
    else
        echo "Running in check-only mode. Run with --update to apply."
    fi

    exit 1  # Exit 1 = changes available (same convention as zstd script)
else
    echo "=== No changes detected ==="
    exit 0
fi
